" display
set guioptions-=T    " disable toolbars(T), see :help guioptions
set guioptions-=rL   " disable scroll bars (rL), see :help guioptions
set guioptions-=t    " disable tear off menus(t), see :help guioptions
set columns=110      " set the display width (includes numberwidth columns)
set lines=66         " force gvim to be full screen

" to workaround vim-sensible plugin changing the sidescrolloff value
" NOTE: can be removed if bug is later fixed in vim-sensible
set sidescrolloff=0

" dialog box
set browsedir=last   " use 'last' dir for file browsing

" in OSX set the focus back the last iTerm instance
if has("gui_macvim")
  autocmd VimLeave * :!open -a iTerm
endif

" run local config options
if filereadable(expand("~/.gvimrc.after"))
  source ~/.gvimrc.after
endif
