" This must be first, because it changes other options as a side effect.
set nocompatible

" Logging method for debugging; Ex: call g:Log('message')
function! g:Log(eventName)
  silent execute '!echo '. a:eventName .' >> log'
endfunction

" for changing defaults like 'mapleader'
if filereadable(expand("~/.vimrc.before"))
  source ~/.vimrc.before
endif

" Change leader because the backslash is too far away
" That means all \x commands turn into <space>x
" WARN: the mapleader has to be set before plugins are loaded.
" IMPORTANT: <space> is mapped to <leader> in vim-keymap.vim. This method
"            allows showcmd to keep working.
" let mapleader = "\<space>"

" Define plugins so they can be installed/uninstalled
" NOTE: Most plugins are loaded between .vimrc and .gvimrc but colorscheme
"       plugins must be made available before sourcing the main dotfile vimrc
"       configs.
"
source ~/.vim/plugins.vim

" Source dotfile repo settings
for fpath in split(glob('~/.vim/settings/*.vim'), '\n')
   exe 'source' fpath
endfor
