" This must be first, because it changes other options as a side effect.
set nocompatible

" for changing defaults like 'mapleader'
if filereadable(expand("~/.vimrc.before"))
  source ~/.vimrc.before
endif

" Change leader because the backslash is too far away
" That means all \x commands turn into ;x
" WARN: the mapleader has to be set before plugins are loaded.
let mapleader = ';'

" define plugins so they can be installed/uninstalled
" NOTE: Most plugins are loaded between .vimrc and .gvimrc but colorscheme
"       plugins must be made available before sourcing the main dotfile vimrc
"       configs.
"
source ~/.vim/plugins.vim

" source dotfile repo settings
for fpath in split(glob('~/.vim/settings/*.vim'), '\n')
   exe 'source' fpath
endfor

" File Settings
"***********************************
if has("autocmd")
   " jump to last known cursor position
   autocmd BufReadPost *
      \ if line("'\"") > 0 && line("'\"") <= line("$") |
      \   exe "normal g`\"" |
      \ endif
   " add pyunit integration into python files (tip 280)
   autocmd FileType python setlocal makeprg=../alltests.py\ -q
   autocmd FileType python setlocal efm=%C\ %.%#,%A\ \ File\ \"%f\"\\,\ line\ %l%.%#,%Z%[%^\ ]%\\@=%m
   " allow for Sphinx '#:' comment delimiters in Python files
   autocmd FileType python setlocal comments+=:#:
endif "has("autocmd")

" Edit Shortcuts
   "find (select word under cursor)
   nnoremap <C-f> /<C-R><C-W>
   inoremap <C-f> <C-O>/<C-R><C-W>
   "find (highlighted text)
   vnoremap <C-f> y/<C-R>=escape(@", '\\/.*$^~[]')<cr>
   vnoremap *     y/<C-R>=escape(@", '\\/.*$^~[]')<cr>
   "reverse find (highlighted text)
   vnoremap #     y?<C-R>=escape(@", '\\/.*$^~[]')<cr>
   "remove highlights after find
   noremap  <silent><Space> :noh<bar>:echo ""<cr>
   "toggle spelling
   nnoremap <silent><F7> :setlocal spell!<cr>
   vnoremap <silent><F7> <C-C>:setlocal spell!<cr>gv
   inoremap <silent><F7> <C-O>:setlocal spell!<cr>

" Session Plugin Settings
"***********************************
set sessionoptions=blank,buffers,curdir,folds,help,resize,tabpages,winsize
" noremap <F1> <C-C>:SessionList<cr>
" noremap <F2> <C-C>:SessionOpenLast<cr>
" noremap <F3> <C-C>:SessionSave<cr>
" noremap <F4> <C-C>:SessionSaveAs<cr>
