# generate the .ssh/config

# add warning header
cat >! $HOME/.ssh/config <<EOF
###                                                      ###
###  AUTO GENERATED BY ~/.dotfiles/zsh/ssh_config.zsh    ###
###                                                      ###

EOF

# append local config if exists, since order matters
if [[ -e $HOME/.ssh/config.local ]]; then
   cat $HOME/.ssh/config.local >> $HOME/.ssh/config
fi

# append files from .ssh/config.d/*
cat $HOME/.dotfiles/ssh/config.d/* >> $HOME/.ssh/config
