#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

## DEBUG
# set -o xtrace -o verbose
# tmux kill-server

# Wait to show any pre-tmux output
sleep 1

# Start TMUX first; try to reattach a session
if [[ -z $TMUX ]]; then
  ATTACH_OPT=$(tmux ls | grep -vq attached && echo "attach -d")
  exec eval "tmux $ATTACH_OPT"
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#
# Source ZSH configs
#
for subdir (zsh terminal git vim python borg)
  for config_file ($HOME/.dotfiles/$subdir/*.zsh(N)) source $config_file

# finalize local config
for config_file ($HOME/.zsh.after/*.zsh(N)) source $config_file

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
