#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# start TMUX first
[[ $TMUX = "" ]] && exec tmux -2

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#
# Source ZSH configs
#
for subdir (zsh terminal git vim)
  for config_file ($HOME/.dotfiles/$subdir/*.zsh(N)) source $config_file

# finalize local config
for config_file ($HOME/.zsh.after/*.zsh(N)) source $config_file
