#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# start TMUX first
if [[ $TMUX = "" ]]; then
  # reset colors
  source $HOME/.dotfiles/terminal/colors.zsh
  # try to reattach sessions
  tmux ls | grep -vq attached && TMUXARG="attach -d"
  exec eval "tmux -2 $TMUXARG"
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

#
# Source ZSH configs
#
for subdir (zsh terminal git vim)
  for config_file ($HOME/.dotfiles/$subdir/*.zsh(N)) source $config_file

# finalize local config
for config_file ($HOME/.zsh.after/*.zsh(N)) source $config_file
